"""
Django settings for fkba_platform project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-k_ed+p5n@758oz16+_@r@)y*2_3=1@7t7eil2z^!yrxv3f8m@p')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'

# Adicionar o domínio de produção e os hosts locais
ALLOWED_HOSTS: list[str] = ['fkba.prolutas.com', 'localhost', '127.0.0.1'] 
# Incluir '127.0.0.1' e 'localhost' para testes e o Caddy


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'core',
    'events',
    'payments',
    'matchmaking',
    'notifications',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fkba_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fkba_platform.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'data' / 'db.sqlite3',
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


if not DEBUG:
    # Configurações de segurança para produção, essenciais para o HTTPS funcionar
    # Esta configuração permite que o Caddy atue como um proxy seguro para o Django
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Configuração de arquivos estáticos e de mídia em produção
    STATIC_URL = '/static/'
    STATIC_ROOT = BASE_DIR / 'staticfiles_prod' # Novo diretório para arquivos estáticos
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media_prod' # Novo diretório para arquivos de mídia


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ASAAS_API_BASE = os.getenv('ASAAS_API_BASE', 'https://sandbox.asaas.com/api/v3')
ASAAS_API_KEY = os.getenv('ASAAS_API_KEY', '')
ASAAS_WEBHOOK_TOKEN = os.getenv('ASAAS_WEBHOOK_TOKEN', '')
ASAAS_DEFAULT_BILLING_TYPE = os.getenv('ASAAS_DEFAULT_BILLING_TYPE', 'PIX')
ASAAS_PAYMENT_DUE_DAYS = int(os.getenv('ASAAS_PAYMENT_DUE_DAYS', '3'))

