# Generated by Django 5.2.6 on 2025-09-25 14:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_alter_athleteregistration_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.CharField(max_length=64)),
                ('asaas_payment_id', models.CharField(max_length=64, unique=True)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('due_date', models.DateField()),
                ('billing_type', models.CharField(choices=[('PIX', 'PIX'), ('BOLETO', 'Boleto'), ('CREDIT_CARD', 'Cartao de credito'), ('UNDEFINED', 'Outro')], default='PIX', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('AWAITING_RISK_ANALYSIS', 'Em analise'), ('RECEIVED', 'Recebido'), ('CONFIRMED', 'Confirmado'), ('OVERDUE', 'Vencido'), ('REFUNDED', 'Reembolsado'), ('REFUND_REQUESTED', 'Reembolso solicitado'), ('CHARGEBACK_REQUESTED', 'Chargeback solicitado'), ('CHARGEBACK_DISPUTE', 'Em disputa'), ('CHARGEBACK_REVERSED', 'Chargeback revertido'), ('BANK_SLIP_VIEWED', 'Boleto visualizado'), ('PAYMENT_DELETED', 'Pagamento removido'), ('UNKNOWN', 'Desconhecido')], default='PENDING', max_length=32)),
                ('invoice_url', models.URLField(blank=True)),
                ('bank_slip_url', models.URLField(blank=True)),
                ('pix_qr_code_image', models.TextField(blank=True)),
                ('pix_copy_and_paste', models.TextField(blank=True)),
                ('external_reference', models.CharField(blank=True, max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='events.athleteregistration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
