# Generated by Django 5.2.6 on 2025-09-24 23:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('registration_deadline', models.DateTimeField(help_text='Data limite para novas inscrições.')),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('rules_document', models.FileField(blank=True, upload_to='event_rules/')),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='AthleteRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('practice_time', models.CharField(choices=[('lt_1', 'Menos de 1 ano'), ('1_3', '1 a 3 anos'), ('3_5', '3 a 5 anos'), ('gt_5', 'Mais de 5 anos')], default='lt_1', max_length=32)),
                ('record_wins', models.PositiveSmallIntegerField(default=0)),
                ('record_draws', models.PositiveSmallIntegerField(default=0)),
                ('record_losses', models.PositiveSmallIntegerField(default=0)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('modality', models.CharField(choices=[('amateur', 'Amador'), ('professional', 'Profissional')], max_length=32)),
                ('whatsapp', models.CharField(max_length=32)),
                ('sex', models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino'), ('other', 'Outro')], max_length=16)),
                ('experience_level', models.CharField(choices=[('beginner', 'Iniciante'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado')], default='beginner', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='pending', max_length=16)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='core.academy')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='core.coach')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
            ],
            options={
                'ordering': ['athlete_name'],
                'unique_together': {('event', 'athlete_name', 'birth_date')},
            },
        ),
    ]
