# Generated by Django 5.2.6 on 2025-09-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='athleteregistration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='athleteregistration',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddConstraint(
            model_name='athleteregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('cpf__isnull', False)), fields=('event', 'cpf'), name='unique_event_cpf'),
        ),
    ]
