# Generated by Django 5.2.6 on 2025-09-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_athleteregistration_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteregistration',
            name='rule_set',
            field=models.CharField(choices=[('k1_light', 'K1 Light'), ('k1_rules', 'K1 Rules')], default='k1_light', max_length=32),
        ),
    ]
