# Arquivo: docker-compose.prod.yml (Final Corrigido)

services:
  # 1. Serviço da Aplicação Django (App)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Carregar variáveis de ambiente do .env
    env_file:
      - ./.env
    # Mapear variáveis de produção no ambiente do contêiner
    environment:
      # Definir chaves de produção (garante que DEBUG=False)
      DJANGO_DEBUG: 'False'
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    # Expor a porta internamente para que o Caddy possa se conectar
    expose:
      - "8000"
    restart: always
    # Volumes para persistência e acesso do Caddy
    volumes:
      - django_db:/usr/src/app/data 
      - django_static:/usr/src/app/staticfiles_prod 
      - django_media:/usr/src/app/media_prod 

  # 2. Serviço de Proxy Reverso Caddy (HTTPS/Reverse Proxy)
  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      # Expor as portas HTTP (80) e HTTPS (443) para o mundo
      - "80:80"
      - "443:443"
    volumes:
      # Mapear o Caddyfile de configuração
      - ./Caddyfile:/etc/caddy/Caddyfile
      - django_static:/usr/src/app/staticfiles_prod
      - django_media:/usr/src/app/media_prod
      # Volume para persistência dos certificados SSL (muito importante!)
      - caddy_data:/data
    depends_on:
      - app

# Volumes para persistência de dados
volumes:
  django_db:
  django_static:
  django_media:
  caddy_data: