from __future__ import annotations

from datetime import date, timedelta
from decimal import Decimal

from django.core.management.base import BaseCommand, CommandError
from django.utils import timezone

from core.models import Academy, Coach
from events.models import AthleteRegistration, Event


class Command(BaseCommand):
    help = 'Cria 40 inscrições de teste com faixas de idade e peso distintas.'

    def add_arguments(self, parser):
        parser.add_argument('--event-id', type=int, help='ID de um evento existente para receber as inscrições.')

    def handle(self, *args, **options):
        event = self._get_or_create_event(options.get('event_id'))
        athletes = self._build_dataset()

        created = 0
        for index, data in enumerate(athletes, start=1):
            academy, _ = Academy.objects.get_or_create(
                name=data['academy'],
                city=data['city'],
                defaults={'state': data['state']},
            )
            coach, _ = Coach.objects.get_or_create(
                full_name=data['coach'],
                academy=academy,
                defaults={'whatsapp': data['whatsapp'], 'email': ''},
            )
            rule_set = data.get('rule_set')
        if not rule_set:
            rule_set = AthleteRegistration.RuleSet.K1_LIGHT if index % 2 else AthleteRegistration.RuleSet.K1_RULES
        defaults = {
                'academy': academy,
                'coach': coach,
                'athlete_name': data['name'],
                'birth_date': data['birth_date'],
                'practice_time': data['practice_time'],
                'rule_set': rule_set,
                'record_wins': data['wins'],
                'record_draws': data['draws'],
                'record_losses': data['losses'],
                'weight_kg': Decimal(str(data['weight_kg'])),
                'modality': data['modality'],
                'whatsapp': data['whatsapp'],
                'sex': data['sex'],
                'status': data['status'],
            }
            _, created_flag = AthleteRegistration.objects.update_or_create(
                event=event,
                cpf=data['cpf'],
                defaults=defaults,
            )
            if created_flag:
                created += 1
        self.stdout.write(self.style.SUCCESS(f'{created} inscrições criadas para o evento "{event.title}".'))

    def _get_or_create_event(self, event_id: int | None) -> Event:
        if event_id:
            try:
                return Event.objects.get(pk=event_id)
            except Event.DoesNotExist:
                raise CommandError(f'Evento com id {event_id} não encontrado.')
        start_at = timezone.now() + timedelta(days=20)
        deadline = start_at - timedelta(days=7)
        event, _ = Event.objects.get_or_create(
            title='Circuito Teste Automático',
            defaults={
                'location': 'Ginásio Municipal',
                'start_at': start_at,
                'registration_deadline': deadline,
                'registration_fee': Decimal('150.00'),
                'is_published': True,
            },
        )
        return event

    def _build_dataset(self) -> list[dict]:
        base = [
            {
                'cpf': '10000000001',
                'name': 'Ana Beatriz Almeida',
                'birth_date': date(2010, 5, 4),
                'practice_time': AthleteRegistration.PracticeDuration.LESS_THAN_ONE,
                'wins': 0,
                'draws': 1,
                'losses': 0,
                'weight_kg': 45.2,
                'modality': AthleteRegistration.Modality.AMATEUR,
                'whatsapp': '5511987654301',
                'sex': AthleteRegistration.Sex.FEMALE,
                'status': AthleteRegistration.Status.PENDING,
                'academy': 'Dragons Kickboxing',
                'coach': 'Marcos Lima',
                'city': 'São Paulo',
                'state': 'SP',
            },
            {
                'cpf': '10000000002',
                'name': 'Bruno Henrique Costa',
                'birth_date': date(2008, 1, 19),
                'practice_time': AthleteRegistration.PracticeDuration.ONE_TO_THREE,
                'wins': 3,
                'draws': 0,
                'losses': 1,
                'weight_kg': 52.4,
                'modality': AthleteRegistration.Modality.AMATEUR,
                'whatsapp': '5511976543210',
                'sex': AthleteRegistration.Sex.MALE,
                'status': AthleteRegistration.Status.PENDING,
                'academy': 'Forja Paulista',
                'coach': 'Ricardo Moreira',
                'city': 'Campinas',
                'state': 'SP',
            },
            {
                'cpf': '10000000003',
                'name': 'Carla Fernanda Diniz',
                'birth_date': date(2002, 9, 12),
                'practice_time': AthleteRegistration.PracticeDuration.THREE_TO_FIVE,
                'wins': 8,
                'draws': 0,
                'losses': 2,
                'weight_kg': 57.9,
                'modality': AthleteRegistration.Modality.PROFESSIONAL,
                'whatsapp': '5511965432109',
                'sex': AthleteRegistration.Sex.FEMALE,
                'status': AthleteRegistration.Status.CONFIRMED,
                'academy': 'Elite Fighters',
                'coach': 'Helena Prado',
                'city': 'Curitiba',
                'state': 'PR',
            },
            {
                'cpf': '10000000004',
                'name': 'Diego Martins Peixoto',
                'birth_date': date(1999, 3, 30),
                'practice_time': AthleteRegistration.PracticeDuration.MORE_THAN_FIVE,
                'wins': 15,
                'draws': 1,
                'losses': 3,
                'weight_kg': 63.5,
                'modality': AthleteRegistration.Modality.PROFESSIONAL,
                'whatsapp': '5511954321098',
                'sex': AthleteRegistration.Sex.MALE,
                'status': AthleteRegistration.Status.CONFIRMED,
                'academy': 'Garra Team',
                'coach': 'Maurício Braga',
                'city': 'Rio de Janeiro',
                'state': 'RJ',
            },
            {
                'cpf': '10000000005',
                'name': 'Eduarda Moraes Lima',
                'birth_date': date(2006, 7, 8),
                'practice_time': AthleteRegistration.PracticeDuration.ONE_TO_THREE,
                'wins': 2,
                'draws': 2,
                'losses': 1,
                'weight_kg': 48.7,
                'modality': AthleteRegistration.Modality.AMATEUR,
                'whatsapp': '5511943210987',
                'sex': AthleteRegistration.Sex.FEMALE,
                'status': AthleteRegistration.Status.PENDING,
                'academy': 'Hurricane Combat',
                'coach': 'Patrícia Reis',
                'city': 'Belo Horizonte',
                'state': 'MG',
            },
            {
                'cpf': '10000000006',
                'name': 'Felipe Araújo Pires',
                'birth_date': date(1995, 11, 22),
                'practice_time': AthleteRegistration.PracticeDuration.MORE_THAN_FIVE,
                'wins': 20,
                'draws': 2,
                'losses': 4,
                'weight_kg': 71.0,
                'modality': AthleteRegistration.Modality.PROFESSIONAL,
                'whatsapp': '5511932109876',
                'sex': AthleteRegistration.Sex.MALE,
                'status': AthleteRegistration.Status.CONFIRMED,
                'academy': 'Impacto Fight Club',
                'coach': 'Gustavo Fagundes',
                'city': 'Florianópolis',
                'state': 'SC',
            },
            {
                'cpf': '10000000007',
                'name': 'Gabriel Monteiro Sales',
                'birth_date': date(2004, 2, 14),
                'practice_time': AthleteRegistration.PracticeDuration.THREE_TO_FIVE,
                'wins': 6,
                'draws': 1,
                'losses': 2,
                'weight_kg': 68.4,
                'modality': AthleteRegistration.Modality.AMATEUR,
                'whatsapp': '5511921098765',
                'sex': AthleteRegistration.Sex.MALE,
                'status': AthleteRegistration.Status.PENDING,
                'academy': 'Thunder Kickboxing',
                'coach': 'Rafael Teles',
                'city': 'Sorocaba',
                'state': 'SP',
            },
            {
                'cpf': '10000000008',
                'name': 'Helena Duarte Prado',
                'birth_date': date(1993, 4, 9),
                'practice_time': AthleteRegistration.PracticeDuration.MORE_THAN_FIVE,
                'wins': 18,
                'draws': 0,
                'losses': 4,
                'weight_kg': 61.8,
                'modality': AthleteRegistration.Modality.PROFESSIONAL,
                'whatsapp': '5511910987654',
                'sex': AthleteRegistration.Sex.FEMALE,
                'status': AthleteRegistration.Status.CONFIRMED,
                'academy': 'Forja Paulista',
                'coach': 'Ricardo Moreira',
                'city': 'Campinas',
                'state': 'SP',
            },
            {
                'cpf': '10000000009',
                'name': 'Igor Figueiredo Nunes',
                'birth_date': date(2007, 6, 3),
                'practice_time': AthleteRegistration.PracticeDuration.LESS_THAN_ONE,
                'wins': 1,
                'draws': 0,
                'losses': 1,
                'weight_kg': 49.0,
                'modality': AthleteRegistration.Modality.AMATEUR,
                'whatsapp': '5511909876543',
                'sex': AthleteRegistration.Sex.MALE,
                'status': AthleteRegistration.Status.PENDING,
                'academy': 'Nova Geração',
                'coach': 'Elaine Martins',
                'city': 'Guarulhos',
                'state': 'SP',
            },
            {
                'cpf': '10000000010',
                'name': 'Júlia Campos Vieira',
                'birth_date': date(2003, 8, 27),
                'practice_time': AthleteRegistration.PracticeDuration.ONE_TO_THREE,
                'wins': 5,
                'draws': 2,
                'losses': 1,
                'weight_kg': 55.6,
                'modality': AthleteRegistration.Modality.AMATEUR,
                'whatsapp': '5511898765432',
                'sex': AthleteRegistration.Sex.FEMALE,
                'status': AthleteRegistration.Status.CONFIRMED,
                'academy': 'Elite Fighters',
                'coach': 'Helena Prado',
                'city': 'Curitiba',
                'state': 'PR',
            },
            {
                'cpf': '10000000011',
                'name': 'Kaio Vinícius Borges',
                'birth_date': date(1998, 12, 18),
                'practice_time': AthleteRegistration.PracticeDuration.MORE_THAN_FIVE,
                'wins': 14,
                'draws': 3,
                'losses': 5,
                'weight_kg': 78.2,
                'modality': AthleteRegistration.Modality.PROFESSIONAL,
                'whatsapp': '5511887654321',
                'sex': AthleteRegistration.Sex.MALE,
                'status': AthleteRegistration.Status.CONFIRMED,
                'academy': 'Garra Team',
                'coach': 'Maurício Braga',
                'city': 'Rio de Janeiro',
                'state': 'RJ',
            },
            {
                'cpf': '10000000012',
                'name': 'Lívia Fernandes Rocha',
                'birth_date': date(1997, 7, 2),
                'practice_time': AthleteRegistration.PracticeDuration.THREE_TO_FIVE,
                'wins': 9,
                'draws': 1,
                'losses': 2,
                'weight_kg': 59.4,
                'modality': AthleteRegistration.Modality.PROFESSIONAL,
                'whatsapp': '5511876543210',
                'sex': AthleteRegistration.Sex.FEMALE,
                'status': AthleteRegistration.Status.CONFIRMED,
                'academy': 'Storm Muay Thai',
                'coach': 'Danilo Carvalho',
                'city': 'Fortaleza',
                'state': 'CE',
            },
            {
                'cpf': '10000000013',
                'name': 'Mateus Costa Silveira',
                'birth_date': date(2005, 11, 1),
                'practice_time': AthleteRegistration.PracticeDuration.ONE_TO_THREE,
                'wins': 4,
                'draws': 0,
                'losses': 2,
                'weight_kg': 66.9,
                'modality': AthleteRegistration.Modality.AMATEUR,
                'whatsapp': '5511865432109',
                'sex': AthleteRegistration.Sex.MALE,
                'status': AthleteRegistration.Status.PENDING,
                'academy': 'Hurricane Combat',
                'coach': 'Patrícia Reis',
                'city': 'Belo Horizonte',
                'state': 'MG',
            },
            {
                'cpf': '10000000014',
                'name': 'Nathalia Rezende Souza',
                'birth_date': date(2001, 10, 15),
                'practice_time': AthleteRegistration.PracticeDuration.THREE_TO_FIVE,
                'wins': 7,
                'draws': 1,
                'losses': 2,
                'weight_kg': 58.1,
                'modality': AthleteRegistration.Modality.PROFESSIONAL,
                'whatsapp': '5511854321098',
                'sex': AthleteRegistration.Sex.FEMALE,
                'status': AthleteRegistration.Status.CONFIRMED,
                'academy': 'Forja Paulista',
                'coach': 'Ricardo Moreira',
                'city': 'Campinas',
                'state': 'SP',
            },
            {
                'cpf': '10000000015',
                'name': 'Otávio Ribeiro Gomes',
                'birth_date': date(2009, 9, 7),
                'practice_time': AthleteRegistration.PracticeDuration.LESS_THAN_ONE,
                'wins': 1,
                'draws': 0,
                'losses': 0,
                'weight_kg': 47.8,
                'modality': AthleteRegistration.Modality.AMATEUR,
                'whatsapp': '5511843210987',
                'sex': AthleteRegistration.Sex.MALE,
                'status': AthleteRegistration.Status.PENDING,
                'academy': 'Dragons Kickboxing',
                'coach': 'Marcos Lima',
                'city': 'São Paulo',
                'state': 'SP',
            },
            {
                'cpf': '10000000016',
                'name': 'Paula Cristina Andrade',
                'birth_date': date(1994, 6, 11),
                'practice_time': AthleteRegistration.PracticeDuration.MORE_THAN_FIVE,
                'wins': 16,
                'draws': 2,
                'losses': 3,
                'weight_kg': 64.3,
                'modality': AthleteRegistration.Modality.PROFESSIONAL,
                'whatsapp': '5511832109876',
                'sex': AthleteRegistration.Sex.FEMALE,
                'status': AthleteRegistration.Status.CONFIRMED,
                'academy': 'Impacto Fight Club',
                'coach': 'Gustavo Fagundes',
                'city': 'Florianópolis',
                'state': 'SC',
            },
            {
                'cpf': '10000000017',
                'name': 'Rafael Dias Portela',
                'birth_date': date(2000, 4, 4),
                'practice_time': AthleteRegistration.PracticeDuration.THREE_TO_FIVE,
                'wins': 10,
                'draws': 2,
                'losses': 4,
                'weight_kg': 73.6,
                'modality': AthleteRegistration.Modality.PROFESSIONAL,
                'whatsapp': '5511821098765',
                'sex': AthleteRegistration.Sex.MALE,
                'status': AthleteRegistration.Status.CONFIRMED,
                'academy': 'Nova Geração',
                'coach': 'Elaine Martins',
                'city': 'Guarulhos',
                'state': 'SP',
            },
            {
                'cpf': '10000000018',
                'name': 'Sofia Martins Pacheco',
                'birth_date': date(2002, 2, 21),
                'practice_time': AthleteRegistration.PracticeDuration.ONE_TO_THREE,
                'wins': 6,
                'draws': 1,
                'losses': 1,
                'weight_kg': 53.9,
                'modality': AthleteRegistration.Modality.AMATEUR,
                'whatsapp': '5511810987654',
                'sex': AthleteRegistration.Sex.FEMALE,
                'status': AthleteRegistration.Status.PENDING,
                'academy': 'Storm Muay Thai',
                'coach': 'Danilo Carvalho',
                'city': 'Fortaleza',
                'state': 'CE',
            },
            {
                'cpf': '10000000019',
                'name': 'Tiago Augusto Rios',
                'birth_date': date(1991, 1, 6),
                'practice_time': AthleteRegistration.PracticeDuration.MORE_THAN_FIVE,
                'wins': 22,
                'draws': 1,
                'losses': 3,
                'weight_kg': 82.5,
                'modality': AthleteRegistration.Modality.PROFESSIONAL,
                'whatsapp': '5511809876543',
                'sex': AthleteRegistration.Sex.MALE,
                'status': AthleteRegistration.Status.CONFIRMED,
                'academy': 'Garra Team',
                'coach': 'Maurício Braga',
                'city': 'Rio de Janeiro',
                'state': 'RJ',
            },
            {
                'cpf': '10000000020',
                'name': 'Vitória Lopes Guimarães',
                'birth_date': date(2008, 12, 25),
                'practice_time': AthleteRegistration.PracticeDuration.LESS_THAN_ONE,
                'wins': 1,
                'draws': 1,
                'losses': 0,
                'weight_kg': 50.3,
                'modality': AthleteRegistration.Modality.AMATEUR,
                'whatsapp': '5511798765432',
                'sex': AthleteRegistration.Sex.FEMALE,
                'status': AthleteRegistration.Status.PENDING,
                'academy': 'Dragons Kickboxing',
                'coach': 'Marcos Lima',
                'city': 'São Paulo',
                'state': 'SP',
            },
        ]

        extras = [
            {
                'cpf': '10000000021',
                'name': 'Alexandre Nunes',
                'birth_date': date(2005, 3, 18),
                'practice_time': AthleteRegistration.PracticeDuration.ONE_TO_THREE,
                'wins': 4,
                'draws': 0,
                'losses': 1,
                'weight_kg': 61.5,
                'modality': AthleteRegistration.Modality.AMATEUR,
                'whatsapp': '551191122334',
                'sex': AthleteRegistration.Sex.MALE,
                'status': AthleteRegistration.Status.PENDING,
                'academy': 'Lions Kickboxing',
                'coach': 'Paulo Araujo',
                'city': 'Belo Horizonte',
                'state': 'MG',
            },
            {
                'cpf': '10000000022',
                'name': 'Bianca Carvalho',
                'birth_date': date(2006, 7, 22),
                'practice_time': AthleteRegistration.PracticeDuration.THREE_TO_FIVE,
                'wins': 9,
                'draws': 1,
                'losses': 2,
                'weight_kg': 56.2,
                'modality': AthleteRegistration.Modality.AMATEUR,
                'whatsapp': '551192233445',
                'sex': AthleteRegistration.Sex.FEMALE,
                'status': AthleteRegistration.Status.CONFIRMED,
                'academy': 'Power Strike',
                'coach': 'Juliana Prado',
                'city': 'Sorocaba',
                'state': 'SP',
            },
            {
                'cpf': '10000000023',
                'name': 'Caio Menezes',
                'birth_date': date(1998, 11, 3),
                'practice_time': AthleteRegistration.PracticeDuration.MORE_THAN_FIVE,
                'wins': 15,
                'draws': 2,
                'losses': 4,
                'weight_kg': 78.9,
                'modality': AthleteRegistration.Modality.PROFESSIONAL,
                'whatsapp': '551193344556',
                'sex': AthleteRegistration.Sex.MALE,
                'status': AthleteRegistration.Status.CONFIRMED,
                'academy': 'Thunder Warriors',
                'coach': 'Felipe Castro',
                'city': 'Porto Alegre',
                'state': 'RS',
            },
            {
                'cpf': '10000000024',
                'name': 'Daniela Rocha',
                'birth_date': date(2001, 1, 30),
                'practice_time': AthleteRegistration.PracticeDuration.ONE_TO_THREE,
                'wins': 5,
                'draws': 0,
                'losses': 1,
                'weight_kg': 59.4,
                'modality': AthleteRegistration.Modality.AMATEUR,
                'whatsapp': '551194455667',
                'sex': AthleteRegistration.Sex.FEMALE,
                'status': AthleteRegistration.Status.PENDING,
                'academy': 'Elite Combat',
                'coach': 'Renata Dias',
                'city': 'Brasilia',
                'state': 'DF',
            },
            {
                'cpf': '10000000025',
                'name': 'Eduardo Campos',
                'birth_date': date(2007, 12, 14),
                'practice_time': AthleteRegistration.PracticeDuration.LESS_THAN_ONE,
                'wins': 1,
                'draws': 1,
                'losses': 0,
                'weight_kg': 49.8,
                'modality': AthleteRegistration.Modality.AMATEUR,
                'whatsapp': '551195566778',
                'sex': AthleteRegistration.Sex.MALE,
                'status': AthleteRegistration.Status.PENDING,
                'academy': 'Jaguars Fight Team',
                'coach': 'Leandro Pires',
                'city': 'Recife',
                'state': 'PE',
            },
            {
                'cpf': '10000000026',
                'name': 'Fernanda Torres',
                'birth_date': date(1995, 5, 9),
                'practice_time': AthleteRegistration.PracticeDuration.MORE_THAN_FIVE,
                'wins': 18,
                'draws': 3,
                'losses': 5,
                'weight_kg': 65.7,
                'modality': AthleteRegistration.Modality.PROFESSIONAL,
                'whatsapp': '551196677889',
                'sex': AthleteRegistration.Sex.FEMALE,
                'status': AthleteRegistration.Status.CONFIRMED,
                'academy': 'Impacto Fight Club',
                'coach': 'Gustavo Fagundes',
                'city': 'Florianopolis',
                'state': 'SC',
            },
            {
                'cpf': '10000000027',
                'name': 'Gabriel Almeida',
                'birth_date': date(2004, 8, 26),
                'practice_time': AthleteRegistration.PracticeDuration.THREE_TO_FIVE,
                'wins': 7,
                'draws': 2,
                'losses': 2,
                'weight_kg': 70.3,
                'modality': AthleteRegistration.Modality.AMATEUR,
                'whatsapp': '551197788990',
                'sex': AthleteRegistration.Sex.MALE,
                'status': AthleteRegistration.Status.PENDING,
                'academy': 'Nova Geracao',
                'coach': 'Elaine Martins',
                'city': 'Guarulhos',
                'state': 'SP',
            },
            {
                'cpf': '10000000028',
                'name': 'Helena Martins',
                'birth_date': date(2012, 2, 15),
                'practice_time': AthleteRegistration.PracticeDuration.LESS_THAN_ONE,
                'wins': 0,
                'draws': 0,
                'losses': 0,
                'weight_kg': 42.6,
                'modality': AthleteRegistration.Modality.AMATEUR,
                'whatsapp': '551198899001',
                'sex': AthleteRegistration.Sex.FEMALE,
                'status': AthleteRegistration.Status.PENDING,
                'academy': 'Storm Muay Thai',
                'coach': 'Danilo Carvalho',
                'city': 'Fortaleza',
                'state': 'CE',
            },
            {
                'cpf': '10000000029',
                'name': 'Igor Pereira',
                'birth_date': date(1993, 4, 11),
                'practice_time': AthleteRegistration.PracticeDuration.MORE_THAN_FIVE,
                'wins': 20,
                'draws': 2,
                'losses': 6,
                'weight_kg': 84.4,
                'modality': AthleteRegistration.Modality.PROFESSIONAL,
                'whatsapp': '551700112233',
                'sex': AthleteRegistration.Sex.MALE,
                'status': AthleteRegistration.Status.CONFIRMED,
                'academy': 'Garra Team',
                'coach': 'Mauricio Braga',
                'city': 'Rio de Janeiro',
                'state': 'RJ',
            },
            {
                'cpf': '10000000030',
                'name': 'Juliana Silva',
                'birth_date': date(1999, 10, 2),
                'practice_time': AthleteRegistration.PracticeDuration.THREE_TO_FIVE,
                'wins': 11,
                'draws': 1,
                'losses': 3,
                'weight_kg': 62.1,
                'modality': AthleteRegistration.Modality.PROFESSIONAL,
                'whatsapp': '556234567890',
                'sex': AthleteRegistration.Sex.FEMALE,
                'status': AthleteRegistration.Status.CONFIRMED,
                'academy': 'Phoenix Warriors',
                'coach': 'Adriana Luz',
                'city': 'Goiania',
                'state': 'GO',
            },
            {
                'cpf': '10000000031',
                'name': 'Kaua Oliveira',
                'birth_date': date(2008, 6, 18),
                'practice_time': AthleteRegistration.PracticeDuration.ONE_TO_THREE,
                'wins': 2,
                'draws': 0,
                'losses': 1,
                'weight_kg': 54.7,
                'modality': AthleteRegistration.Modality.AMATEUR,
                'whatsapp': '558212345678',
                'sex': AthleteRegistration.Sex.MALE,
                'status': AthleteRegistration.Status.PENDING,
                'academy': 'Street Fighters',
                'coach': 'Joel Santana',
                'city': 'Maceio',
                'state': 'AL',
            },
            {
                'cpf': '10000000032',
                'name': 'Larissa Prado',
                'birth_date': date(2003, 9, 9),
                'practice_time': AthleteRegistration.PracticeDuration.THREE_TO_FIVE,
                'wins': 8,
                'draws': 2,
                'losses': 2,
                'weight_kg': 58.0,
                'modality': AthleteRegistration.Modality.AMATEUR,
                'whatsapp': '551523456789',
                'sex': AthleteRegistration.Sex.FEMALE,
                'status': AthleteRegistration.Status.PENDING,
                'academy': 'Power Strike',
                'coach': 'Juliana Prado',
                'city': 'Sorocaba',
                'state': 'SP',
            },
            {
                'cpf': '10000000033',
                'name': 'Marcelo Tavares',
                'birth_date': date(1988, 12, 20),
                'practice_time': AthleteRegistration.PracticeDuration.MORE_THAN_FIVE,
                'wins': 25,
                'draws': 4,
                'losses': 6,
                'weight_kg': 90.5,
                'modality': AthleteRegistration.Modality.PROFESSIONAL,
                'whatsapp': '554123456789',
                'sex': AthleteRegistration.Sex.MALE,
                'status': AthleteRegistration.Status.CONFIRMED,
                'academy': 'Iron Gladiators',
                'coach': 'Bruno Serafim',
                'city': 'Curitiba',
                'state': 'PR',
            },
            {
                'cpf': '10000000034',
                'name': 'Natalia Moura',
                'birth_date': date(2005, 11, 27),
                'practice_time': AthleteRegistration.PracticeDuration.ONE_TO_THREE,
                'wins': 6,
                'draws': 1,
                'losses': 1,
                'weight_kg': 55.3,
                'modality': AthleteRegistration.Modality.AMATEUR,
                'whatsapp': '551199887766',
                'sex': AthleteRegistration.Sex.FEMALE,
                'status': AthleteRegistration.Status.CANCELLED,
                'academy': 'Dragons Kickboxing',
                'coach': 'Marcos Lima',
                'city': 'Sao Paulo',
                'state': 'SP',
            },
            {
                'cpf': '10000000035',
                'name': 'Otavio Linhares',
                'birth_date': date(1997, 7, 8),
                'practice_time': AthleteRegistration.PracticeDuration.MORE_THAN_FIVE,
                'wins': 14,
                'draws': 3,
                'losses': 3,
                'weight_kg': 76.6,
                'modality': AthleteRegistration.Modality.PROFESSIONAL,
                'whatsapp': '551923456780',
                'sex': AthleteRegistration.Sex.MALE,
                'status': AthleteRegistration.Status.CONFIRMED,
                'academy': 'Forja Paulista',
                'coach': 'Ricardo Moreira',
                'city': 'Campinas',
                'state': 'SP',
            },
            {
                'cpf': '10000000036',
                'name': 'Paula Costa',
                'birth_date': date(2000, 3, 25),
                'practice_time': AthleteRegistration.PracticeDuration.THREE_TO_FIVE,
                'wins': 9,
                'draws': 0,
                'losses': 2,
                'weight_kg': 60.7,
                'modality': AthleteRegistration.Modality.PROFESSIONAL,
                'whatsapp': '556112345679',
                'sex': AthleteRegistration.Sex.FEMALE,
                'status': AthleteRegistration.Status.CONFIRMED,
                'academy': 'Elite Combat',
                'coach': 'Renata Dias',
                'city': 'Brasilia',
                'state': 'DF',
            },
            {
                'cpf': '10000000037',
                'name': 'Rafael Lima',
                'birth_date': date(2009, 1, 13),
                'practice_time': AthleteRegistration.PracticeDuration.LESS_THAN_ONE,
                'wins': 1,
                'draws': 0,
                'losses': 1,
                'weight_kg': 48.9,
                'modality': AthleteRegistration.Modality.AMATEUR,
                'whatsapp': '558112345680',
                'sex': AthleteRegistration.Sex.MALE,
                'status': AthleteRegistration.Status.PENDING,
                'academy': 'Jaguars Fight Team',
                'coach': 'Leandro Pires',
                'city': 'Recife',
                'state': 'PE',
            },
            {
                'cpf': '10000000038',
                'name': 'Sabrina Oliveira',
                'birth_date': date(1996, 4, 6),
                'practice_time': AthleteRegistration.PracticeDuration.MORE_THAN_FIVE,
                'wins': 17,
                'draws': 2,
                'losses': 4,
                'weight_kg': 67.8,
                'modality': AthleteRegistration.Modality.PROFESSIONAL,
                'whatsapp': '556223456781',
                'sex': AthleteRegistration.Sex.FEMALE,
                'status': AthleteRegistration.Status.CONFIRMED,
                'academy': 'Phoenix Warriors',
                'coach': 'Adriana Luz',
                'city': 'Goiania',
                'state': 'GO',
            },
            {
                'cpf': '10000000039',
                'name': 'Tiago Matos',
                'birth_date': date(2002, 8, 29),
                'practice_time': AthleteRegistration.PracticeDuration.THREE_TO_FIVE,
                'wins': 10,
                'draws': 1,
                'losses': 2,
                'weight_kg': 73.2,
                'modality': AthleteRegistration.Modality.PROFESSIONAL,
                'whatsapp': '554723456782',
                'sex': AthleteRegistration.Sex.MALE,
                'status': AthleteRegistration.Status.PENDING,
                'academy': 'Thunder Warriors',
                'coach': 'Felipe Castro',
                'city': 'Porto Alegre',
                'state': 'RS',
            },
            {
                'cpf': '10000000040',
                'name': 'Valeria Souza',
                'birth_date': date(2004, 4, 5),
                'practice_time': AthleteRegistration.PracticeDuration.ONE_TO_THREE,
                'wins': 4,
                'draws': 1,
                'losses': 1,
                'weight_kg': 59.9,
                'modality': AthleteRegistration.Modality.AMATEUR,
                'whatsapp': '553123456783',
                'sex': AthleteRegistration.Sex.FEMALE,
                'status': AthleteRegistration.Status.PENDING,
                'academy': 'Lions Kickboxing',
                'coach': 'Paulo Araujo',
                'city': 'Belo Horizonte',
                'state': 'MG',
            },
        ]
        return base + extras
