# Generated by Django 5.2.6 on 2025-09-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchmakingMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('weight_divisions', models.JSONField(blank=True, default=list)),
                ('experience_divisions', models.JSONField(blank=True, default=list)),
                ('modality_categories', models.JSONField(blank=True, default=list)),
                ('age_divisions', models.JSONField(blank=True, default=list)),
                ('max_fights_per_athlete', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
