# Generated by Django 5.2.6 on 2025-09-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmakingmetric',
            name='age_divisions',
        ),
        migrations.RemoveField(
            model_name='matchmakingmetric',
            name='experience_divisions',
        ),
        migrations.RemoveField(
            model_name='matchmakingmetric',
            name='modality_categories',
        ),
        migrations.RemoveField(
            model_name='matchmakingmetric',
            name='weight_divisions',
        ),
        migrations.AddField(
            model_name='matchmakingmetric',
            name='category_blocks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
