
# Generated by Django 5.2.6 on 2025-09-26 01:40

from django.db import migrations, models
import matchmaking.models


def copy_category_blocks_to_new_fields(apps, schema_editor):
    MatchmakingMetric = apps.get_model('matchmaking', 'MatchmakingMetric')
    for metric in MatchmakingMetric.objects.all():
        if hasattr(metric, 'category_blocks') and metric.category_blocks:
            metric.weight_categories = metric.category_blocks
        if not metric.age_metrics:
            metric.age_metrics = [
                {'name': 'infantil', 'min_age': 9, 'max_age': 11},
                {'name': 'cadete', 'min_age': 12, 'max_age': 14},
                {'name': 'juvenil', 'min_age': 15, 'max_age': 17},
                {'name': 'adulto', 'min_age': 18, 'max_age': 40},
            ]
        if not metric.experience_metrics:
            metric.experience_metrics = [
                {'name': 'iniciante', 'max_fights': 4},
                {'name': 'avancado', 'min_fights': 5},
            ]
        metric.save(update_fields=['age_metrics', 'experience_metrics', 'weight_categories'])


def remove_category_blocks_field(apps, schema_editor):
    # Nothing special required; Django will handle removal.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_remove_matchmakingmetric_age_divisions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmakingmetric',
            name='age_metrics',
            field=models.JSONField(blank=True, default=matchmaking.models.default_age_metrics),
        ),
        migrations.AddField(
            model_name='matchmakingmetric',
            name='experience_metrics',
            field=models.JSONField(blank=True, default=matchmaking.models.default_experience_metrics),
        ),
        migrations.AddField(
            model_name='matchmakingmetric',
            name='weight_categories',
            field=models.JSONField(blank=True, default=matchmaking.models.default_weight_categories),
        ),
        migrations.RunPython(copy_category_blocks_to_new_fields, remove_category_blocks_field),
        migrations.RemoveField(
            model_name='matchmakingmetric',
            name='category_blocks',
        ),
    ]
