# Generated by Django 5.2.6 on 2025-09-26 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_athleteregistration_rule_set'),
        ('matchmaking', '0003_remove_matchmakingmetric_category_blocks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchmakingBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_set', models.CharField(choices=[('k1_light', 'K1 Light'), ('k1_rules', 'K1 Rules')], max_length=32)),
                ('experience_label', models.CharField(max_length=64)),
                ('sex', models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino'), ('other', 'Outro')], max_length=16)),
                ('age_group', models.CharField(max_length=32)),
                ('weight_label', models.CharField(max_length=32)),
                ('bracket_index', models.PositiveSmallIntegerField(default=1)),
                ('size', models.PositiveSmallIntegerField(help_text='Numero total de vagas na chave')),
                ('max_fights', models.PositiveSmallIntegerField()),
                ('is_manual', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchmaking_brackets', to='events.event')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_brackets', to=settings.AUTH_USER_MODEL)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brackets', to='matchmaking.matchmakingmetric')),
            ],
            options={
                'ordering': ['event', 'rule_set', 'experience_label', 'sex', 'age_group', 'weight_label', 'bracket_index'],
                'unique_together': {('event', 'metric', 'rule_set', 'experience_label', 'sex', 'age_group', 'weight_label', 'bracket_index')},
            },
        ),
        migrations.CreateModel(
            name='MatchmakingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seed', models.PositiveSmallIntegerField()),
                ('slot', models.PositiveSmallIntegerField()),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='matchmaking.matchmakingbracket')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchmaking_entries', to='events.athleteregistration')),
            ],
            options={
                'ordering': ['slot'],
                'unique_together': {('bracket', 'registration'), ('bracket', 'slot')},
            },
        ),
        migrations.CreateModel(
            name='MatchmakingMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round_number', models.PositiveSmallIntegerField()),
                ('position', models.PositiveSmallIntegerField()),
                ('is_bye', models.BooleanField(default=False)),
                ('blue_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_blue', to='matchmaking.matchmakingentry')),
                ('blue_source_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_as_blue', to='matchmaking.matchmakingmatch')),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matchmaking.matchmakingbracket')),
                ('red_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_red', to='matchmaking.matchmakingentry')),
                ('red_source_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_as_red', to='matchmaking.matchmakingmatch')),
                ('winner_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins_as_winner', to='matchmaking.matchmakingentry')),
            ],
            options={
                'ordering': ['round_number', 'position'],
            },
        ),
    ]
